name: Build the APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x Android-APK-Project/gradlew

      - name: Build with Gradle
        run: cd Android-APK-Project && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BandersPotatoERP-apk
          path: Android-APK-Project/app/build/outputs/apk/debug/*.apk

